name: nx-cypress-record

on:
  workflow_dispatch:

env:
  # Set up the Cypress Cloud project ID and record key as environment variables
  # If the Actions variable EXAMPLE_PROJECT_ID is not defined then
  # the projectId is taken from cypress.config.ts
  CYPRESS_PROJECT_ID: ${{ vars.EXAMPLE_PROJECT_ID }}
  CYPRESS_RECORD_KEY: ${{ secrets.EXAMPLE_RECORDING_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  store-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          command: npx nx e2e store-e2e
          record: true

  store-2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npx nx serve store
          working-directory: apps/store-e2e
          config: baseUrl=http://localhost:4200
          record: true
